clone_folder: c:\go\src\github.com\google\pprof

install:
 - cinst graphviz.portable

before_build:
 - go get github.com/ianlancetaylor/demangle

build_script:
 - go build github.com/google/pprof

test_script:
  - go test -v ./...
