clone_folder: c:\go\src\github.com\google\pprof

install:
 - ps: choco install graphviz
 
before_build:
 - go get github.com/ianlancetaylor/demangle

build_script:
 - go build github.com/google/pprof

test_script:
  - go test -v ./...
