clone_folder: c:\gopath\src\github.com\google\pprof

environment:
  GOPATH: c:\gopath

install:
 - cinst graphviz

build_script:
 - go env
 - go build github.com/google/pprof

test_script:
  - go test -v ./...
