clone_folder: c:\go\src\github.com\google\pprof

install:
 - cinst graphviz.portable
 
before_build:
 - go get github.com/ianlancetaylor/demangle

build_script:
 - go build github.com/google/pprof
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi

test_script:
  - go test -v ./...
